### ISSUE TITLE
not displaying properly

### ISSUE THREAD

**Issue by sgmckenna** [v-braun/VBRRollingPit#1]
Just found your great tabbar enhancement on cocoacontrols. However, its not displaying properly. what am I doing wrong. I installed via pods. 
See attached.
![image-1](https://user-images.githubusercontent.com/1414339/43550687-6f412692-95b2-11e8-970d-3f8f1cea2467.jpg)

**Comment by v-braun** [comment]
The bar and the circle have both background colors and can be specified separately.
It looks like your background is white and thats why it looks so strange :)

Just set the colors in the attribute inspector:
![image](https://user-images.githubusercontent.com/4738210/43589029-28b03544-966e-11e8-9cda-3b842c64efde.png)

or through code

please reply if that was helpfull and/or you have an idea to prevent such issues for other users.
Maybe another default color??

**Comment by sgmckenna** [comment]
I beli
![screen shot 2018-08-02 at 16 27 29](https://user-images.githubusercontent.com/1414339/43609178-49e9b2dc-9671-11e8-8ad2-e5df71b1fa23.png)
eve I have them set at default.
