### ISSUE TITLE
Tab Bar Background 

### ISSUE THREAD

**Issue by mertbaser** [v-braun/VBRRollingPit#10]
I cannot change the tab-bar background color

I'm trying to edit it in the interface builder

![image](https://user-images.githubusercontent.com/44214351/49618751-ba5a7300-f9ca-11e8-91f0-d5bc7da41235.png)

My goal is to have a transparent background (getting rid of that black background)

**Comment by v-braun** [comment]
@mertbaser have you found a solution on that?
Could you write down how you solved your issue that I can reference it for others?

**Comment by mertbaser** [comment]
@v-braun I had to add another "View" and match its color with the background

![image](https://user-images.githubusercontent.com/44214351/49696492-5ea30c00-fbbb-11e8-97a0-9c5652da5a75.png)

**Comment by v-braun** [comment]
looks like a workaround.
is it possible to provide me the source code of your app (or create an example with that issue)?
The problem with the background was already raised by multiple persons but it is not reproducible for me :(
