### ISSUE TITLE
Stop Circular Movement animation

### ISSUE THREAD

**Issue by adelbios** [v-braun/VBRRollingPit#14]
how I. can stop Circular animation based on status like if user doesn't login into my app 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16545509/69731681-01d59400-1133-11ea-9148-086779fe88cc.gif)

I called self.selectedIndex = 2 to return circle to main Index but I wanna to check if tabBar Index != 2 // stop movement

**Comment by v-braun** [comment]
Did I get it right? You want to disable the entire control?
So no of the buttons can be navigated until your user is logged in?
I would recommend not to show the control than or at least disable it so that the user see that no action is possible.

**Comment by adelbios** [comment]
@v-braun yes this is right, can u give me example code to do this ?!

**Comment by v-braun** [comment]
Why not hide it or show the login screen without the bar?
I mean built a login screen without a TabBar on it?
Or If you want to make some of your views accessable without a login, don't propagate the pages to the navigation controller that needs the authentication.
That would hide automatically all of your Buttons that are not accessable.

**Comment by adelbios** [comment]
@v-braun but i have 5 tabBarItem 
Index 2 && index 4 must be clickable Other index must be login , so who i can do this to stop circle movement animation

**Comment by v-braun** [comment]
This feature I have never considered. Can you hide index 2 & 4?
That you have at the end only 3 buttons till the user is authenticated?

**Comment by adelbios** [comment]
okay no problem let's me work on this feature

**Comment by v-braun** [comment]
I'm talking about something like this: https://medium.com/@dinarajas/dynamic-tabbar-items-in-runtime-a94b357df1c5

Will close this issue for now.
