### ISSUE TITLE
TabBarItem's badge icon position for non selected tab.

### ISSUE THREAD

**Issue by AnandSharma0821** [v-braun/VBRRollingPit#19]
@v-braun & @Kladdkaka How to manage the badge icon position for non selected tab. Here I am sending you the screenshot for your reference. Can you please provide us a way to manage the badge icon.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-24 at 12 41 53](https://user-images.githubusercontent.com/71649978/94226515-68733c00-ff15-11ea-9058-e62e964de918.png)

**Comment by v-braun** [comment]
You have to position it yourself, check this out:
https://stackoverflow.com/a/38973225

**Comment by AnandSharma0821** [comment]
@v-braun Thanks for your reply. It helped me to change the position of the badge item. There is one weird issue which I am facing, in a few devices tab bar is showing a separator line as shown in the below attachment.
<img width="610" alt="Separator" src="https://user-images.githubusercontent.com/71649978/95062375-82cdc680-071a-11eb-80ad-1003c6da9b22.png">

Can you please help me out with this?

**Comment by v-braun** [comment]
Looks like there is a system style that provides this separator (maybe a special ios version or something else). It only happens on specific devices right? have they another ios version??

Maybe this will help (the last sentence in the post):
https://blog.k.io/atech/set-the-top-border-colour-of-a-uinavbar

> In order to hide the system border, I have found that it’s usually enough to simply set the clipsToBounds property on the tab bar to true.
```
self.tabBar.clipsToBounds = YES;
```

**Comment by AnandSharma0821** [comment]
@v-braun Thanks for the support. That worked for me.
