### ISSUE TITLE
Crash after adding manually 

### ISSUE THREAD

**Issue by bhoomesh950** [v-braun/VBRRollingPit#2]
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /var/containers/Bundle/Application/5A0970D5-3344-4A67-AE33-F60AA715382A/BubbleTransition.app/BubbleTransition
  Reason: image not found
Message from debugger: Terminated due to signal 6

**Comment by v-braun** [comment]
What do you mean, you added it manually?
Just copy&paste the class (which class) into your existing project?
What swift version are you using?

**Comment by v-braun** [comment]
Are you sure we are talking about the same lib?
In your Error there is a **BubbleTransition.app** bundle and thats looks for me like this [lib](https://github.com/andreamazz/BubbleTransition)
