### ISSUE TITLE
How do I only include the image in the circle and make it centered of the selected tab?

### ISSUE THREAD

**Issue by binayathapamagar** [v-braun/VBRRollingPit#24]
I need to make the image appear in the selected tab's circle centered and leave the title of the selected tab on the tab controller below the selected tab's circle.

**Comment by binayathapamagar** [comment]
I need to make only the image appear in the selected tab's circle centered and leave the title of the selected tab on the tab controller below the selected tab's circle.

**Comment by v-braun** [comment]
This is not related on this lib, it is a requiement for the TabBar Controller / TabBar View.

You can try to hide the title on the tabbar item and somehow implement a label that will be shown below the tabbar item.

**Comment by binayathapamagar** [comment]
Will do! Thanks for the response.
