### ISSUE TITLE
Memory leaks 

### ISSUE THREAD

**Issue by bhoomesh950** [v-braun/VBRRollingPit#4]
<img width="1010" alt="screen shot 2018-08-17 at 3 56 40 pm" src="https://user-images.githubusercontent.com/20543788/44261755-44bd7200-a236-11e8-9ff3-06c671937822.png">
<img width="460" alt="screen shot 2018-08-17 at 3 56 55 pm" src="https://user-images.githubusercontent.com/20543788/44261757-46873580-a236-11e8-9237-06a213cc8028.png">

I have added RollingPitTabbar.swift manually in an objective c project it's working well but when i run the project in instruments i have found memory leaks.
![screen shot 2018-08-17 at 3](https://user-images.githubusercontent.com/20543788/44261651-ebedd980-a235-11e8-8022-7c7b7644a9c6.jpg)
 

please find the attachment.

**Comment by v-braun** [comment]
Sorry but I cannot reproduce that:
![image](https://user-images.githubusercontent.com/4738210/46905919-bc3c1480-cefa-11e8-985f-aa0096f3ac66.png)

Could you describe more in detail what you have done and provide example code?

**Comment by v-braun** [comment]
I checked the code and the only problem case that I see there is that animations would not be removed. I have fixed that now. Not sure that this is your case.
see commit 9f0436f49c46d2fc41b4af47c7b282bb93a906d5
