### ISSUE TITLE
it showing black color on top of tabbar

### ISSUE THREAD

**Issue by kirti301290** [v-braun/VBRRollingPit#5]
hello
your  developed good control for tabbar
i have implemented in  objective c project  but is showing black color on tababr
attached  screenshot here
how to resolve this problem
![screenshot 2018-10-08 at 11 09 45 pm](https://user-images.githubusercontent.com/10956919/46624965-e8007880-cb4f-11e8-943f-28b51ef95cc0.png)

**Comment by v-braun** [comment]
Sorry I didn't sure that I understood you correctly!
You are working on an Objective-C Project and try to use that Lib there?
Or are you trying to reimplement this control in Objective-C?

It looks like the background have a black color.
Without a look at your code it is not possible for me to say what that (black) background is. To be sure simply set all views in your StoreyBuilder to a transparent image or provide me your code!?

**Comment by kirti301290** [comment]
thanks for your reply
i dropped your swift file in objective c project 
and given  tabbar child class to RollingPitTabBar in Storyboard and all image in PNG format
i have not did  any code  for this 
thanks

**Comment by v-braun** [comment]
I see! 
But is there a view **behind** the TabBar? 
It looks like there is much more on your scene than only the TabBar.
Could you create a complete new and empty ViewController with only a TabBar and change there the base class?

**Comment by kirti301290** [comment]
thanks for quick reply
i checked as per your suggestion and it working fine in only empty ViewController
but what if ViewController has tableview or another controller in it showing black 
i have given bottom side minus padding and it working fine 
but if ViewController's view   has white color then it not showing tabbar  i would it you help me to give shadow of  uitabbar here is attached screenshot

![screenshot 2018-10-09 at 11 03 07 pm](https://user-images.githubusercontent.com/10956919/46687396-717b7d80-cc18-11e8-9587-454029c4790c.png)
![screenshot 2018-10-09 at 11 02 45 pm](https://user-images.githubusercontent.com/10956919/46687409-7c361280-cc18-11e8-817f-3a6e214a5932.png)

**Comment by kirti301290** [comment]
Pls help me if possible
i want to implement like this screenshot
viewcontroller view color is white but tabbar show perfectly because of tabbar shadow

![screenshot 2018-10-09 at 11 34 46 pm](https://user-images.githubusercontent.com/10956919/46688870-13e93000-cc1c-11e8-983e-bd52c810b836.png)

**Comment by v-braun** [comment]
Hi, 
sounds good that it works now.
I don't know why the tableviewcontroller has a black background. Maybe there are some "black" layers that should be configured correctly.
You could also align the tableviewcontroller above the tabbar and not "below" it.

Regarding the shadow: your welcome to create a contribution on this lib and implement the shadow by yourself.
Otherwise, create a separate Issue and tag it as an enhancement.
If I find the time I will have a look at it.
