### ISSUE TITLE
How to stop selected tab animation

### ISSUE THREAD

**Issue by kirti301290** [v-braun/VBRRollingPit#7]
Hello
your control is good but how to  stop  movement with  circle
want to only central tab menu is round circle rest will be not change

want to look like this
![screenshot 2018-10-20 at 10 13 13 pm](https://user-images.githubusercontent.com/10956919/47258204-70b6d700-d4b5-11e8-8aad-322ec3278022.png)

**Comment by v-braun** [comment]
Hi,

I'm not sure that I have understood your feature request correctley!
You don't want any animation or that the selected element is highlighted?
That is the wrong component for your requirement!
What you want is simple to implement! I see there two buttons on a view and a button with round corners.
It would make more effort to implement it into this component than do a specific solution.
