### ISSUE TITLE
Need Transparent Bg

### ISSUE THREAD

**Issue by syedrazackimran** [v-braun/VBRRollingPit#9]
Hi, 

I working with your lib. it looks good UI, but I have several doubts. kindly help me. Thanks in advance.

1. when I run with iOS 12.1 I didn't get the shadow of your tab bar, but I gotta shadow in 12.
2. How I can remove that background I need transparent, once that tab bar and circle. I will attach a screenshot for ur reference.
3. Animation when I select tab bar I icon move's top first and then circle move to the index. I need to do move both at the same time.

kindly do needfully

![simulator screen shot - iphone xs max - 2018-11-29 at 17 55 10](https://user-images.githubusercontent.com/15051045/49217452-2a339100-f400-11e8-927d-d775f47e428f.png)
![simulator screen shot - iphone xs max - 2018-11-29 at 17 55 15](https://user-images.githubusercontent.com/15051045/49217453-2acc2780-f400-11e8-977c-c2d74e3541b4.png)

**Comment by v-braun** [comment]
Hey,

first of all: have you modified the code or use it as it is?

1.: In general there are now shadows (see also my example screenshoot). Are you sure that you don't have set a shadow by yourself? Can you provide your code that I can check that?
2. Simply set the BackgroundColor of the TabBar to Transparent. In general it has it per default. Again: could you provide your code? There is no shadow/background in the demo.
3.: The duration of the "hide" animation and their duration is here: 
https://github.com/v-braun/VBRRollingPit/blob/cb2a709e7dadeecd85526b181b7014166f57a11d/VBRRollingPit/VBRRollingPit/RollingPitTabBar.swift#L237 

the roll animation is here:
https://github.com/v-braun/VBRRollingPit/blob/cb2a709e7dadeecd85526b181b7014166f57a11d/VBRRollingPit/VBRRollingPit/RollingPitTabBar.swift#L247

simply adjust these two values.

**Comment by SaFaa-Mohamed1** [comment]
How to reduce the animation of move circle?

**Comment by v-braun** [comment]
close because of inactivity

**Comment by gizmeondev** [comment]
Hey @v-braun , same issue here. Your RollingPitTabBar also includes the portion covered in the red rectangle of the above screenshot. So basically if we add a view(like tableview in screenshot) inside the viewcontroller, we can see a blank space from the bottom of the view to the tabbar. 

![](https://user-images.githubusercontent.com/15051045/49217453-2acc2780-f400-11e8-977c-c2d74e3541b4.png)

**Comment by hamedazhar** [comment]
Hey @v-braun, same issue here. Your RollingPitTabBar also includes the portion covered in the red rectangle of the above screenshot. So basically if we add a view(like tableview in screenshot) inside the viewcontroller, we can see a blank space from the bottom of the view to the tabbar.

![](https://user-images.githubusercontent.com/15051045/49217453-2acc2780-f400-11e8-977c-c2d74e3541b4.png)

**Comment by syedrazackimran** [comment]
[RollingPit.zip](https://github.com/v-braun/VBRRollingPit/files/3050040/RollingPit.zip)

Hi hello,

herewith I added sample projects kindly check it once.

**Comment by v-braun** [comment]
@syedrazackimran & @hamedazhar 
the BG is transparent. You have a View (on root level) with a grey Baground and your CollectionView has constraints that say they should be within the safearea of that view.
Looks for me that you use a ViewController instead of a CollectionViewController to represent your data.
See the screenshoot and compare the view hierarchies.
"Item Scene" works as expected because the collection view is expanded over the entire screen (and is also behind the TabBar).

![image](https://user-images.githubusercontent.com/4738210/55670379-b27ce380-5883-11e9-9b97-689cf8d18e42.png)
